version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.2
    - 10.1.3
  - dependency-name: socket.io-client
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: socket.io
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: postcss-loader
    versions:
    - 5.0.0
    - 5.1.0
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
  - dependency-name: react-table
    versions:
    - 7.6.3
  - dependency-name: raw-loader
    versions:
    - 4.0.1
